### ISSUE TITLE
デモビデオ

### ISSUE THREAD

**Issue by sidestepism** [sidestepism/Vibrat-o-matic#14]
- [x] スーザンボイルのカット  (素材キャプチャ)
- [x] ｢ビブラートは難しい｣
- [x] へたなスーザンボイル風の実写 (撮影)
- [x] ｢ビブラートを簡単にしよう｣ システム名  Vibrat-o-matic
- [x] 身体の素材 のどとおなかでかける (イラスト)
- [x] ここにEMSをつけてみた (イラスト)
- [x] オンにするとふるえる (撮影)
- [x] 3-5-7hz いろんなパラメータを試して検討した (撮影)
- [x] そしてかっこいいUIも作った (スクショ撮影)
- [x] したらこんなにうまく歌えるようになったよ (スーザンボイル)
- [x] Features
- [x] Play & Record (スクショ撮影)
- [x] F0を検出してビブラートをかけるべきときにかけることもできる (イラスト)
- [x] 声じゃなくてもリコーダーでも大丈夫 (撮影)
- [x] サックス トランペット フルート 可能性は無限大だ!!! (イラスト)
- [x] Karaoke Time!
- [x] Let it go (撮影)
- [x] 千の風になって (撮影)
- [x] I was born to love you (撮影)
- [x] You can try at UIST SIC Demo! (Tue 17:00-19:30)

**Comment by nawafuji** [comment]
できたー
