### ISSUE TITLE
いい曲を収集

### ISSUE THREAD

**Issue by sidestepism** [sidestepism/Vibrat-o-matic#5]
- 演歌
- ジャズ
- JPop
 - [千の風になって](https://www.youtube.com/watch?v=yqzCwcL9xDc)
- 洋楽

**Comment by nawafuji** [comment]
I was born to love you - Queen
https://www.youtube.com/watch?v=vNhhAEupU4g

**Comment by nawafuji** [comment]
let it go - Frozen 
https://www.youtube.com/watch?v=L0MK7qz13bU

**Comment by sidestepism** [comment]
I dreamed a dream
