### ISSUE TITLE
EMSパッドの配置

### ISSUE THREAD

**Issue by nawafuji** [sidestepism/Vibrat-o-matic#8]
お腹の駆動に最適なパッド配置を摸索。

**Comment by sidestepism** [comment]
@nawafuji Androidのファームアップお願いします〜

**Comment by nawafuji** [comment]
arduinoファーム変えました〜。
チャンネル１のLEDがちらついてるのが少し心配だけど学校着いたらとりあえず試します。

**Comment by nawafuji** [comment]
伏見は縦配置が好み
藤縄は横配置が好み

どう決定したら良いのか・・

**Comment by sidestepism** [comment]
縦配置で決定
