### ISSUE TITLE
ビブラート経験者のヒアリング会

### ISSUE THREAD

**Issue by nawafuji** [sidestepism/Vibrat-o-matic#9]
leonかstjあたりを呼んで試してもらう。
ビブラートに適した波形、周波数ー強さ曲線、パッド配置などについて検討する。

**Comment by nawafuji** [comment]
普通の歌声・ビブラート歌声・EMSビブラート歌声
で波形を観測して比較したい。

**Comment by nawafuji** [comment]
こちらで用意するもの

・エンベロープ波形のバリエーション
・一定時間の周波数ー強さ曲線のバリエーション、もしくは時間を引数とした関数モデル

**Comment by nawafuji** [comment]
# Leonのフィードバック

## 配置について

- 当初へその上に平行に配置したが、お腹に力がはいるのはもっと下の方とのこと。実際へそのの下の方に配置したほうが違和感が少なかった。
- 縦配置したら心臓に響いてヤバイ感じがしたとのこと。

## ビブラートについて

- ビブラートは本来力が抜けた時に起こる現象。なので長音になったときに自然に声帯の力が抜けて出る。周波数や強さは特に意識してコントロールしていない。

## 電気刺激について

- 電気刺激によるお腹の振動に直接連動してビブラートが出るというより、電気刺激でくすぐったくて力が抜けてビブラートが出てしまう。なのでお腹をくすぐられてビブラートが出てしまうのと同等。本当に電気刺激で直接ビブラートを出したいならのどにつけて揺らすほうが早い。

**Comment by sidestepism** [comment]
写真ここにアップしましたー
https://photos.google.com/share/AF1QipMW1kQN-q_r7qrUkvhwvsnozS0SF6VVyE6hwTdrkc-yGBGSWo_h8qHm-C4YYVVBxg?hl=ja&key=WmpEZnUxc1ZiRDk2clFVNEp2ZFY4ZEdzeV9HZjd3
